Traceback (most recent call last):
  File "/usr/share/miniconda/envs/foss4g/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/share/miniconda/envs/foss4g/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/share/miniconda/envs/foss4g/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/share/miniconda/envs/foss4g/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/share/miniconda/envs/foss4g/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/usr/share/miniconda/envs/foss4g/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/usr/share/miniconda/envs/foss4g/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/share/miniconda/envs/foss4g/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
NDVI_AOI = cgls_ds.rio.clip(AOI_poly, crs=4326)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mMissingCRS[0m                                Traceback (most recent call last)
Input [0;32mIn [10][0m, in [0;36m<cell line: 1>[0;34m()[0m
[0;32m----> 1[0m NDVI_AOI [38;5;241m=[39m [43mcgls_ds[49m[38;5;241;43m.[39;49m[43mrio[49m[38;5;241;43m.[39;49m[43mclip[49m[43m([49m[43mAOI_poly[49m[43m,[49m[43m [49m[43mcrs[49m[38;5;241;43m=[39;49m[38;5;241;43m4326[39;49m[43m)[49m

File [0;32m/usr/share/miniconda/envs/foss4g/lib/python3.10/site-packages/rioxarray/raster_dataset.py:380[0m, in [0;36mRasterDataset.clip[0;34m(self, geometries, crs, all_touched, drop, invert, from_disk)[0m
[1;32m    377[0m [38;5;28;01mtry[39;00m:
[1;32m    378[0m     x_dim, y_dim [38;5;241m=[39m _get_spatial_dims([38;5;28mself[39m[38;5;241m.[39m_obj, var)
[1;32m    379[0m     clipped_dataset[var] [38;5;241m=[39m (
[0;32m--> 380[0m         [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_obj[49m[43m[[49m[43mvar[49m[43m][49m
[1;32m    381[0m [43m        [49m[38;5;241;43m.[39;49m[43mrio[49m[38;5;241;43m.[39;49m[43mset_spatial_dims[49m[43m([49m[43mx_dim[49m[38;5;241;43m=[39;49m[43mx_dim[49m[43m,[49m[43m [49m[43my_dim[49m[38;5;241;43m=[39;49m[43my_dim[49m[43m,[49m[43m [49m[43minplace[49m[38;5;241;43m=[39;49m[38;5;28;43;01mTrue[39;49;00m[43m)[49m
[1;32m    382[0m [43m        [49m[38;5;241;43m.[39;49m[43mrio[49m[38;5;241;43m.[39;49m[43mclip[49m[43m([49m
[1;32m    383[0m [43m            [49m[43mgeometries[49m[43m,[49m
[1;32m    384[0m [43m            [49m[43mcrs[49m[38;5;241;43m=[39;49m[43mcrs[49m[43m,[49m
[1;32m    385[0m [43m            [49m[43mall_touched[49m[38;5;241;43m=[39;49m[43mall_touched[49m[43m,[49m
[1;32m    386[0m [43m            [49m[43mdrop[49m[38;5;241;43m=[39;49m[43mdrop[49m[43m,[49m
[1;32m    387[0m [43m            [49m[43minvert[49m[38;5;241;43m=[39;49m[43minvert[49m[43m,[49m
[1;32m    388[0m [43m            [49m[43mfrom_disk[49m[38;5;241;43m=[39;49m[43mfrom_disk[49m[43m,[49m
[1;32m    389[0m [43m        [49m[43m)[49m
[1;32m    390[0m     )
[1;32m    391[0m [38;5;28;01mexcept[39;00m MissingSpatialDimensionError:
[1;32m    392[0m     [38;5;28;01mif[39;00m [38;5;28mlen[39m([38;5;28mself[39m[38;5;241m.[39m_obj[var][38;5;241m.[39mdims) [38;5;241m>[39m[38;5;241m=[39m [38;5;241m2[39m [38;5;129;01mand[39;00m [38;5;129;01mnot[39;00m get_option(
[1;32m    393[0m         SKIP_MISSING_SPATIAL_DIMS
[1;32m    394[0m     ):

File [0;32m/usr/share/miniconda/envs/foss4g/lib/python3.10/site-packages/rioxarray/raster_array.py:901[0m, in [0;36mRasterArray.clip[0;34m(self, geometries, crs, all_touched, drop, invert, from_disk)[0m
[1;32m    849[0m [38;5;124;03m"""[39;00m
[1;32m    850[0m [38;5;124;03mCrops a :obj:`xarray.DataArray` by geojson like geometry dicts.[39;00m
[1;32m    851[0m 
[0;32m   (...)[0m
[1;32m    898[0m [38;5;124;03m    The clipped object.[39;00m
[1;32m    899[0m [38;5;124;03m"""[39;00m
[1;32m    900[0m [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39mcrs [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[0;32m--> 901[0m     [38;5;28;01mraise[39;00m MissingCRS(
[1;32m    902[0m         [38;5;124m"[39m[38;5;124mCRS not found. Please set the CRS with [39m[38;5;124m'[39m[38;5;124mrio.write_crs()[39m[38;5;124m'[39m[38;5;124m.[39m[38;5;124m"[39m
[1;32m    903[0m         [38;5;124mf[39m[38;5;124m"[39m[38;5;132;01m{[39;00m_get_data_var_message([38;5;28mself[39m[38;5;241m.[39m_obj)[38;5;132;01m}[39;00m[38;5;124m"[39m
[1;32m    904[0m     )
[1;32m    905[0m crs [38;5;241m=[39m crs_from_user_input(crs) [38;5;28;01mif[39;00m crs [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m [38;5;28;01melse[39;00m [38;5;28mself[39m[38;5;241m.[39mcrs
[1;32m    906[0m [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39mcrs [38;5;241m!=[39m crs:

[0;31mMissingCRS[0m: CRS not found. Please set the CRS with 'rio.write_crs()'. Data variable: NDVI
MissingCRS: CRS not found. Please set the CRS with 'rio.write_crs()'. Data variable: NDVI

